urls.py
##############################################################################
##############################################################################
##
## Copyright Michael Dales (c) 2008. Made available under
## the Affero GNU Public License - see COPYING file for details.
##
##############################################################################
##############################################################################

from django.conf.urls.defaults import *
from seriouschange import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('seriouschange.signup.views',
    # Example:
    (r'^$', 'signup_page'),
    #(r'^facebook/$', 'signup_facebook'),
    # Uncomment the next line to enable admin documentation:
    #(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line for to enable the admin:
    (r'^admin/(.*)', admin.site.root),
)

urlpatterns += patterns('', (r'^organise/', include('organise.urls')))

urlpatterns += patterns(
    '',
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
    (r'^accounts/pwchange/$', 'django.contrib.auth.views.password_change'),
    (r'^accounts/password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^accounts/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^accounts/reset/done/$', 'django.contrib.auth.views.password_reset_complete'),
)

urlpatterns += patterns('django.views',
     (r'^site_media/(?P<path>.*)$', 'static.serve', 
         {'document_root': settings.MEDIA_ROOT}),
     (r'^media/(?P<path>.*)$', 'static.serve', 
         {'document_root': settings.ADMIN_MEDIA_ROOT}),

)

signup/models.py
##############################################################################
##############################################################################
##############################################################################
###
### seriouschange/signup/models.py
###
### Copyright Michael Dales (c) 2008. Made available under
### the Affero GNU Public License - see COPYING file for details.
###
##############################################################################
##############################################################################

import simplejson 
import urllib

from django.db import models

from seriouschange import settings 
from seriouschange.signup.country import non_uk_countries

GOOGLE_GEOCODE_URL = "http://maps.google.com/maps/geo?key=%s&q=" % settings.GOOGLE_MAPS_API_KEY

##############################################################################
#
class GeoData(models.Model):
    
    request_address = models.CharField(max_length=255, blank=False, null=False)
    result_address = models.CharField(max_length=255, blank=True, null=True)
    lookup_status = models.IntegerField(blank=True, null=True)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    country = models.CharField(max_length=255, blank=True, null=True)
    admin_area = models.CharField(max_length=255, blank=True, null=True)
    
    
    def __unicode__(self):
        return u"%s - %s, %s" % (self.request_address, self.latitude, self.longitude)
    
    def get_location_data(self, raw_address):
        address = urllib.quote(raw_address)
        
        try:
            f = urllib.urlopen(GOOGLE_GEOCODE_URL + address)            
            data = simplejson.load(f)
            f.close()
        except IOError:
            # fail, so just give up
            return
        
        self.request_address = raw_address.lower()
        self.lookup_status = int(data['Status']['code'])
        
        
        if self.lookup_status == 200:
                    
            placemark = data.get('Placemark', [])
            if len(placemark) == 0:
                return
        
            # just go by first placemark
            place = placemark[0]
        
            self.result_address = place['address']
            self.longitude = float(place['Point']['coordinates'][0])
            self.latitude = float(place['Point']['coordinates'][1])
            
            address = place['AddressDetails']
            self.country = address['Country']['CountryName']
            
            if address['Country'].has_key('AdministrativeArea'):
                self.admin_area = address['Country']['AdministrativeArea']['AdministrativeAreaName']
            
        self.save()    
#
##############################################################################


##############################################################################
#
class SignupDetails(models.Model):
    email_address = models.EmailField(blank=False, null=False)
    postcode = models.CharField(max_length=8, blank=True)
    version_string = models.CharField(max_length=255)
    creation_time = models.DateTimeField(blank=False, null=False)
    creation_ipaddr = models.CharField(max_length=15, blank=False, null=False)
    country = models.CharField(max_length=128, blank=False, null=False, 
        default='GB')
    
    location = models.ForeignKey(GeoData, blank=True, null=True)
    
    class Admin:
        pass
        
    def __unicode__(self):
        return u"%s - %s" % (self.email_address, self.postcode)
        
    
    def get_location(self):
        if (self.country == 'GB'):
            address = "%s, UK" % self.postcode
        else: 
            address = None
            for x in non_uk_countries:
                if self.country == x[0]:
                    address = x[1]
            if not address:
                address = self.country
        
        location, created = GeoData.objects.get_or_create(request_address=address.lower())
        
        self.location = location
        if created:
            self.location.get_location_data(address)
        self.save()
        
#
##############################################################################

signup/views.py
##############################################################################
##############################################################################
##############################################################################
###
### seriouschange/signup/views.py
###
### Copyright Michael Dales (c) 2008. Made available under
### the Affero GNU Public License - see COPYING file for details.
###
### Contains the views for the initial basic sign up web site
###
##############################################################################
##############################################################################
##############################################################################

# standard python imports
import datetime
import re

# standard django imports
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect
from django.forms import ModelForm, ValidationError, Form
import django.forms as forms

# serious change imports
from seriouschange.signup.models import SignupDetails
from seriouschange.signup.country import non_uk_countries

#from facebook import Facebook

##############################################################################
#
def _validate_postcode(postcode):
    """Function to validate postcodes by francis"""
    
    # Our test postcode
    if re.match("^zz9\s*9z[zy]$", postcode, re.I):
        return True

    # See http://www.govtalk.gov.uk/gdsc/html/noframes/PostCode-2-1-Release.htm
    _in  = 'ABDEFGHJLNPQRSTUWXYZ';
    fst = 'ABCDEFGHIJKLMNOPRSTUWYZ';
    sec = 'ABCDEFGHJKLMNOPQRSTUVWXY';
    thd = 'ABCDEFGHJKSTUW';
    fth = 'ABEHMNPRVWXY';
    num0 = '123456789'; # Technically allowed in spec, but none exist
    num = '0123456789';
    nom = '0123456789';

    match1 = '^[%s][%s]\s*[%s][%s][%s]$' % \
        (fst, num0, nom, _in, _in)
    match2 = '^[%s][%s][%s]\s*[%s][%s][%s]$' % \
        (fst, num0, num, nom, _in, _in)
    match3 = '^[%s][%s][%s]\s*[%s][%s][%s]$' % \
        (fst, sec, num, nom, _in, _in)
    match4 = '^[%s][%s][%s][%s]\s*[%s][%s][%s]$' % \
        (fst, sec, num0, num, nom, _in, _in)
    match5 = '^[%s][%s][%s]\s*[%s][%s][%s]$' % \
        (fst, num0, thd, nom, _in, _in)
    match6 = '^[%s][%s][%s][%s]\s*[%s][%s][%s]$' % \
        (fst, sec, num0, fth, nom, _in, _in)
        
    match_list = [match1, match2, match3, match4, match5, match6]
    
    pass_val = False
    for match_pattern in match_list:
        if re.match(match_pattern, postcode, re.I):
            pass_val = True
            break
        
    return pass_val
#
##############################################################################



##############################################################################
#
class SignupDetailsForm(Form):
    email_address = forms.EmailField(error_messages = 
        {'required': 'Please enter a valid email address.',
        'invalid': 'Please enter a valid email address.'})
    postcode = forms.CharField(max_length=9, label="Postcode", required=False,
        error_messages = {'required': 'Please enter a valid postcode.'})
    country = forms.ChoiceField(choices=non_uk_countries)
    non_resident = forms.BooleanField(label="Non UK resident", required=False)

    ##########################################################################
    #
    def clean_postcode(self):
        
        if self.is_valid():        
            """we use this method to check that the postcode is valid"""
            postcode = self.cleaned_data['postcode']
               
            try:
                if self.data['non_resident']:
                    return postcode
            except:
                pass
                                
            if len(postcode) == 0:
                raise ValidationError('Please enter a valid postcode.')
            
            if not _validate_postcode(postcode):
                raise ValidationError('Please enter a valid postcode.')
        
            return postcode
    #
    ##########################################################################
    
#
##############################################################################

EMAIL_SUBJECT = "Save iPods and fun fairs from Climate Change"
EMAIL_BODY = """Hi - 

Just found these people, who are stopping Climate Change in
a new way, without the hippies or the denialists.

I think you'll like it.

http://www.seriouschange.org.uk/

<your name>"""



##############################################################################
#
def signup_page(request):
    """This is the basic signup view - asks users for details and then
    forwards them to a 'well done' page."""
    
    if request.method == 'POST':
        signup_form = SignupDetailsForm(request.POST)
        if signup_form.is_valid():
            #new_signup = signup_form.save(commit=False)
            new_signup = SignupDetails()
            new_signup.email_address = signup_form.cleaned_data['email_address']
            new_signup.postcode = signup_form.cleaned_data['postcode']
            new_signup.creation_time = datetime.datetime.now()
            new_signup.creation_ipaddr = request.META['REMOTE_ADDR']
            new_signup.version_string = request.POST['version']
            if signup_form.cleaned_data['non_resident']:
                new_signup.country = signup_form.data['country']
            else:
                new_signup.country = "GB"
            new_signup.save()
            
            new_signup.get_location()
                
            
            # return to the main org view after creation
            return render_to_response('welldone.html', 
                {'email_subject': EMAIL_SUBJECT, 
                'email_body': EMAIL_BODY})
        else:
            # any errors is used to invoke a little bit of javascript 
            # that moves the focus of the page to the form
            any_errors = True
                    
    else:
        signup_form = SignupDetailsForm()
        any_errors = False
        
    return render_to_response('signup.html', {'form': signup_form, 'error': any_errors})
#
##############################################################################


##############################################################################
#
def signup_facebook(request):
    
    # old keys no longer valid, need to get from settings
    #fb = Facebook(settings.FACEBOOK1, settings.FACEBOOK2)
    
    if 'session_key' in request.session and 'uid' in request.session:
        fb.session_key = request.session['session_key']
        fb.uid = request.session['uid']
    else:
        
        try:
            fb.auth_token = request.GET['auth_token']
        except KeyError:
            # Send user to the Facebook to login
            return HttpResponseRedirect(fb.get_login_url())

        # getSession sets the session_key and uid
        # Store these in the cookie so we don't have to get them again
        fb.auth.getSession()
        request.session['session_key'] = fb.session_key
        request.session['uid'] = fb.uid

    
        
    info = fb.users.getInfo([fb.uid], ['name', 'current_location', 'email_hashes'])[0]
    
    return render_to_response('facebook.html', {'info': info, 'fb': fb})
#
##############################################################################

signup/templates/base_signup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
	
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<title>Begone denialists and crusties - Climate Change for the rest of us</title>
	<link rel="stylesheet" href="/site_media/css/fonts-min.css" type="text/css" media="screen" title="no title" charset="utf-8">
	<link rel="stylesheet" href="/site_media/css/reset-min.css" type="text/css" media="screen" title="no title" charset="utf-8">
	<link rel="stylesheet" href="/site_media/css/style.css" type="text/css" media="screen" title="no title" charset="utf-8">
	
{% block script %}
{% endblock %}

</head>

<body>
	{% block content %}
	{% endblock %}

<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
var pageTracker = _gat._getTracker("UA-6325598-1");
pageTracker._trackPageview();
</script>
</body>
</html>

signup/templates/signup.html
{% extends "base_signup.html" %}

{% block script %}
<script type="text/javascript" src="/site_media/jquery-1.2.6.min.js"></script>

<script>
	
function update_form()
{
	if ($("input#id_non_resident").attr("checked"))
	{
		$("#id_country").parent().show();
		$("#id_postcode").parent().hide();
	}
	else
	{
		$("#id_country").parent().hide();
		$("#id_postcode").parent().show();
	}
}
	
$(document).ready(function()
	{
		// the temptation here is to use changed rather than click,
		// but IE doesn't work with that
		$("input#id_non_resident").unbind('click').click(update_form);
		update_form();
	}
);
</script>
{% endblock %}


{% block content %}
	
<table width="100%" border="0">
	<tr>
		<td align="left">
			<h1 id="sigh">Serious<br>Change</h1>
		</td>
		<td>
				<object width="325" height="244" id="video">
		<param name="movie"
		 	value="http://www.youtube.com/v/20dsve4-DSI&hl=en&fs=1">
		</param>
		<param name="allowFullScreen" value="true"></param>
		<param name="allowscriptaccess" value="always"></param>
		<embed src="http://www.youtube.com/v/20dsve4-DSI&hl=en&fs=1" 
			type="application/x-shockwave-flash" 
			allowscriptaccess="always" 
			allowfullscreen="true" 
			width="325" height="244">		
		</embed>
	</object>
		</td>
</table>

<p id="p1">It&#8217;s <strong>very clear</strong> to everyone now that we need to do something to prevent climate change. But what do we do?</p> 

<p id="p2">To one side we're being told that so long as we change to energy saving light bulbs and turn off our phone chargers we'll be okay - a nice start, but we need more than that. On the other side we've got people who think we need to end our current civilisation as we know it - no more travel, no more enjoyable goods, no more communication - this can't be a good idea. Add to that the current global financial crisis - surely we can't manage all of this at once?</p>


<p id="p11">But that's exactly what we're campaigning for - SERIOUS CHANGE that will both save the climate, our lifestyles, and <strong>the economy</strong>!</p>

<p id="p3">To keep the civilisation we've built, we need a secure climate to live in and secure energy to power everything around us. We need solutions that add up, and actions to be taken <strong>now</strong>. Whilst personal actions are good, it requires <strong>governmental action</strong> to provide the economic environment to make this work, and to kick start the low-carbon economy in this country. Then the private sector can get to creating new solutions (thus creating much needed jobs).
</p>

<div id="p4outer">
  <div id="p4inner">
    
  <!--<p>By taking a lead in becoming a low-carbon economy we'll be securing our country's future, both for ourselves and for future generations home and abroad.</p>-->
	<p>By taking a lead in becoming a low-carbon economy we'll be securing our country's future.</p>
  
  <p>That's why we've set up SERIOUS CHANGE - to provide pressure to make sure that government does not ignore the issues, the evidence, and the advice out there. We want the government to focus on a low-carbon agenda as both a way to <strong>solve our environmental plight tomorrow and our economical plight today</strong>	.</p>
  </div>
</div>


<div id="p5outer">
  <div id="p5inner">
    <form action="#form" method="post" id="form">
      <p id="p5">By signing up, you can help:
		<ul class="reasonlist">
<li>Your details help us show that lots of people care about this issue, and will help persuade the powers that be that we expect them to care too.</li>

<li>We'll keep you informed of what SERIOUS CHANGE is going, and ask you to get involved where you can.</li></ul></p>
      <ol> 
        {% for field in form %}
          <li>
            {% if field.errors %}
              <span class="error">{{ field.errors|join:", " }}</span><br>
            {% endif %}
            {{ field.label_tag }} 
            {{ field }} 
          </li>
        {% endfor %}
      </ol>
      <input type="hidden" name="version" value="mwdrewrite"/>
      <input type="submit" class="submit" value="Sign up"/>
    </form>
  </div>
</div>


<div id="faq">
  <h2>FAQ</h2>    

	<em>Sounds great! How can I get more involved?</em>
	
	<p id="p7">We've got a whole web where you can <a href="http://create.seriouschange.org.uk/Create_Serious_Change">find out more and learn about how you can help out</a>. If you think you can help us, then drop us an email at the address below!</p>
	

  <em>Who are you and why should I give you my email address?</em>

  <p id="p7">You’re giving your email to Serious Change, a new unincorporated member association (read our <a href="http://wiki.seriouschange.org.uk/Statement_of_beliefs">statement of beliefs</a>). The founders of Serious Change ran a successful campaign against the Legislative and Regulatory Reform Bill in 2006. Now we are going to stop climate change.</p>
	
  <p>Just email us (<a href="mailto:hello@seriouschange.org.uk">hello@seriouschange.org.uk</a>) if you want to know more.</p>
</div> 



{% endblock %}

signup/templates/welldone.html
{% extends "base_signup.html" %}

{% block content %}
	
<p><strong>Thank you</strong> - we'll get back in touch.
	
	
<p><a href="mailto:?subject={{email_subject|urlencode}}&body={{email_body|urlencode}}">Click here to open a new email and invite your friends, family and colleagues to get involved.</a></p>

<p>Email us at <a href="mailto:hello@seriouschange.org.uk">hello@seriouschange.org.uk</a> if you have something to say.<br><br></p>

<p>	
<table>
	<tr>
		<td>
			<script>function fbs_click() {u='http://www.seriouschange.org.uk/';t=document.title;window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}</script><style> html .fb_share_link { padding:2px 0 0 20px; height:16px; background:url(http://static.ak.fbcdn.net/images/share/facebook_share_icon.gif?2:26981) no-repeat top left; }</style><a href="http://www.facebook.com/share.php?u=<url>" onclick="return fbs_click()" target="_blank" class="fb_share_link">Share on Facebook</a>
		</td>
		<td>&nbsp;&nbsp;</td>
		<td>
			<script>function bebo_click() {u='http://www.seriouschange.org.uk/';t=document.title;window.open('http://www.bebo.com/c/share?Url='+encodeURIComponent(u)+'&t='+encodeURIComponent(t),'sharer','toolbar=0,status=0,width=626,height=436');return false;}</script><style> html .b_share_link { padding:2px 0 0 20px; height:16px; background:url(http://s.bebo.com/img/bebo_b_16x16.gif) no-repeat top left; }</style><a href="http://www.bebo.com/c/share?Url=<url>" onclick="return bebo_click()" target="_blank" class="b_share_link">Share on Bebo</a>
		</td>
	</tr>
</table>
</p>
	
	
	
{% endblock %}